project: visual-flow
imagePullSecret: vf-image-pull

backend:
  createRoles: true
  serviceAccount: 
    name: vf-app-backend
    addSA: true
  deployment:
    replicas: 1
    image:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.13.1-backend
      pullPolicy: Always
    # variables:
    secretVariables:
      KEYSTORE_PASS: "b4hAz8QYVJxDUpv"
      SLACK_API_TOKEN: ""
    sslSecret: vf-app-backend-ssl
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 300m
        memory: 2Gi
  configFile:
    oauth:
      userInfo: "https://api.github.com/user"
      fieldsMap:
        id: id
        username: login
        name: name
        email: email
    superusers: []
    namespace:
      label: vf-app
      prefix: "vf-"
      annotations: {}
    argo:
      serverUrl: "http://vf-app-argo-server.svc:2746"
      limits:
        cpu: 0.5
        memory: 512Mi
      requests:
        cpu: 0.1
        memory: 64Mi
    sparkJob:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.13.1-spark-job
      jobSA: spark
      jobRB: spark-edit
      addSA: true
      # kubernetesAPI: "k8s://https://kubernetes.default.svc.cluster.local"
    slackJob:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.13.1-slack-notification
      appAPItoken: "${SLACK_API_TOKEN}"
  service:
    type: NodePort
    port: 8080
    # nodePort:
    annotations: {}
  subPath: "/vf/be"
  external:
    enabled: false
    type: ingress
    host: localhost
    annotations: {}
    ssl: {}

frontend:
  deployment:
    replicas: 1
    image:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.13.1-frontend
      pullPolicy: Always
    variables:
      STRATEGY: GITHUB
      API_SERVER: "https://vf-app-backend:8080/vf/be/"
      STRATEGY_CALLBACK_URL: "https://localhost/vf/ui/callback"
      GITHUB_STRATEGY_BASE_URL: "https://github.com"
    secretVariables:
      GITHUB_APP_ID: ""
      GITHUB_APP_SECRET: ""
      SESSION_SECRET: "a597d68350b02f2d"
    sslSecret: vf-app-frontend-ssl
    resources: {}
  service:
    type: LoadBalancer
    port: 443
    # nodePort:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
  subPath: "/vf/ui/"
  external:
    enabled: false
    type: ingress
    host: localhost
    annotations: {}
    ssl: {}
