project: visual-flow
imagePullSecret: vf-image-pull

backend:
  createRoles: true
  serviceAccount: 
    name: vf-app-backend
    addSA: true
  deployment:
    replicas: 1
    image:
      repository: ibagomel/visual-flow-backend
      tag: latest
      pullPolicy: Always
    # variables:
    secretVariables:
      KEYSTORE_PASS: "RANDOM_KEYSTORE_PASS"
      SLACK_API_TOKEN: ""
    sslSecret: vf-app-backend-ssl
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 300m
        memory: 2Gi
  configFile:
    oauth:
      userInfo: "https://api.github.com/user"
      fieldsMap:
        id: id
        username: login
        name: name
        email: email
    superusers: []
    namespace:
      label: vf-app
      prefix: "vf-"
      annotations: {}
    argo:
      serverUrl: "http://argo-server.<namespace>.svc:2746"
      limits:
        cpu: 0.5
        memory: 512Mi
      requests:
        cpu: 0.1
        memory: 64Mi
    sparkJob:
      repository: ibagomel/visual-flow-spark-job
      tag: latest
      jobSA: spark
      jobRB: spark-edit
      addSA: true
      # kubernetesAPI: "k8s://https://kubernetes.default.svc.cluster.local"
    slackJob:
      repository: ibagomel/visual-flow-slack-notification
      tag: latest
      appAPItoken: "${SLACK_API_TOKEN}"
  service:
    type: ClusterIP
    port: 8080
    # nodePort:
    annotations: {}
  subPath: "/vf/be"
  external:
    enabled: true
    type: ingress
    host: localhost
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ssl: {}

frontend:
  deployment:
    replicas: 1
    image:
      repository: ibagomel/visual-flow-frontend
      tag: latest
      pullPolicy: IfNotPresent
    variables:
      STRATEGY: GITHUB
      API_SERVER: "https://vf-app-backend:8080/vf/be/"
      STRATEGY_CALLBACK_URL: "https://localhost/vf/ui/callback"
      GITHUB_STRATEGY_BASE_URL: "https://github.com"
    secretVariables:
      GITHUB_APP_ID: ""
      GITHUB_APP_SECRET: ""
      SESSION_SECRET: "RANDOM_SESSION_SECRET"
    sslSecret: vf-app-frontend-ssl
    resources: {}
  service:
    type: ClusterIP
    port: 443
    # nodePort:
    annotations: {}
  subPath: "/vf/ui/"
  external:
    enabled: true
    type: ingress
    host: localhost
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ssl: {}
